### ISSUE TITLE
Ne marche pas chez moi

### ISSUE THREAD

**Issue by qaniere** [Max1Truc/classement-ecoledirecte#1]
1er trimestre: ? / ?
Relevé : ? / ?
2ème trimestre: ? / ?
Relevé : ? / ?
Examen Blanc 1: ? / ?
3ème trimestre: ? / ?
Relevé : ? / ?
Examen Blanc 2: ? / ?
Année: ? / ?

Par contre l'extension Mozilla marche mais pas pour les moyennes générales, que matière par matiére

**Comment by Max1Truc** [comment]
C'est donc que ton établissement a bien paramétré EcoleDirecte ^^

**Comment by Max1Truc** [comment]
En fait, certains établissements, en plus de les cacher, ne calculent tout simplement pas les classements, ce qui empêche cet outil de fonctionner.

**Comment by qaniere** [comment]
D'accord merci
